### ISSUE TITLE
Login and Registration page Views

### ISSUE THREAD

**Issue by edrisranjbar** [kiahamedi/medadfeshari#23]
Hi; as you know, registration and login pages are not good. we need some CSS or bootstrap there to make it more comfortable and user friendly.
and also:
there is a text there "Captcha: " which is not required or maybe we can change it to something Persian.

**Comment by edrisranjbar** [comment]
**Login password checker**
we should have something like live password checker. that do these things:
- compare password and repeat password fields
- check password is valid (with color red, orange,green or whatever)

These things are **IMPORTANT** because it took about 5 to 8 minutes to create an account for me. thats a big number for a simple sign up.

we should work on it.
Thank you.

**Comment by kiahamedi** [comment]
Hi edris
yeah i know and exist best template with bootstrap for login and register in front end directory source
but i no time for changed this parts If you can change these parts I'll be happy ;)
If not, I'll change these parts in the future

**Comment by edrisranjbar** [comment]
of course @kiahamedi  ; i'll be happy too to work on it. time is limited but there is a lot of small times that we can help each other grow an open source community.
I opened it again to say thank you and maybe in the future i ask and check your feedback for changes.

**Comment by kiahamedi** [comment]
Thank you very much
I'm happy and sure we will be working in the open source community in the future
